### ISSUE TITLE
completion framework config not working?

### ISSUE THREAD

**Issue by saadparwaiz1** [steelsojka/pears.nvim#12]
Thank you for a great plugin.

I tried out the recently updated readme for compe but it doesn't seem to work.  I think it might be because compe#confirm returns the key that needs to be pressed. So it might need something like nvim_feedkeys

**Comment by ram02z** [comment]
I am experiencing the same issue.

**Comment by saadparwaiz1** [comment]
@ram02z  made [this](https://github.com/saadparwaiz1/dotfiles/blob/a1e89af910b8548bd16b64c3168d5816e38d7b13/nvim/lua/extensions/packer/init.lua#L41) change to the config to get it working.  Try if this works for you :)

**Comment by ram02z** [comment]
@saadparwaiz1 just tried and it works perfect. Thanks!

**Comment by steelsojka** [comment]
Thanks for finding this! I updated the implementation and docs. You can return any string out of that function now and it will be fed to `feedkeys`. So, just return the result of the compe call.

**Comment by saadparwaiz1** [comment]
Ah thanks for your help 😁
