### ISSUE TITLE
Failed to confirm and expand vsnip

### ISSUE THREAD

**Issue by ray-x** [steelsojka/pears.nvim#15]
Following the README.md. The plugin can work with compe regarding function/field completion. But it failed to expand the vsnip.
There is a related topic https://github.com/hrsh7th/nvim-compe/issues/99 and seems autopairs fixed this issue.
Is it possible to merge the changes or update the README?

**Comment by ray-x** [comment]
There is a bug in the config and prevent my setup function from running successfully, which cause this issue.
I created a RP for this https://github.com/steelsojka/pears.nvim/pull/16

**Comment by steelsojka** [comment]
I merged your PR. Does this work correctly now?

**Comment by ray-x** [comment]
Yes works fine now

**Comment by shubham-cpp** [comment]
Its not working for me. My setup is here
```lua
    use {
        'steelsojka/pears.nvim',
        config = function()
            -- require"pears".setup()
            require"pears".setup(function(conf)
                conf.preset "tag_matching"
                conf.on_enter(function(pears_handle)
                    if vim.fn.pumvisible() == 1 and
                        vim.fn.complete_info().selected ~= -1 then
                        return vim.fn["compe#confirm"]("<CR>")
                    else
                        pears_handle()
                    end
                end)
            end)
            require'helper'.map("i", "<C-l>",
                                "<cmd>lua require\"pears\".expand()<cr>")
        end
    }
```

Whenever I try to expand any snippet it just passes enter instead of expanding the snippet
