### ISSUE TITLE
question: is it possible to insert pair only when enter is pressed?

### ISSUE THREAD

**Issue by elianiva** [steelsojka/pears.nvim#18]
The only reason why I use autopair is to avoid manually creating a multiline pair like these:

```rust
{
  |
}

[
  |
]
```

is it possible to insert the pair *only* when I press enter? When I press `{`, I don't want it to insert `{}`, but when I press `{` and then `<CR>`, it will insert the pair *and* expand it. Some illustration:

```rust
| <- cursor here
{| <- no pair inserted
{
  | <- I pressed enter
}
```

I have something like this in my config but it's not that good and I want to use this plugin for its other features like html closing tag. Thanks in advance!

**Comment by steelsojka** [comment]
Currently there is not a way to do this. I've never really thought of that scenario before. I will look into seeing if it can fit into the current hooks and if not, I'll see if I can add it in.
