### ISSUE TITLE
Add expansion based on treesitter context

### ISSUE THREAD

**Issue by steelsojka** [steelsojka/pears.nvim#2]
Basically, allow expanding only within specific treesitter nodes. This should be completely opt in and configurable.

**Comment by cloggier** [comment]
Would be nice if it allowed for expanding html tags only within html range (injected or otherwise), seems like `windwp/nvim-ts-autotag` does that. But am not sue whether there even exist concept of a html tag in pears. Just a thought.

**Comment by steelsojka** [comment]
This should be mostly work now. Except you can't configure specific nodes, just language detection for nested languages. I want to eventually get configuration for specific nodes. So I'll leave this open until I do.

**Comment by steelsojka** [comment]
I'm closing this since the rules api now contains a `child_of_node` rule that can be applied to any part of expansion based on a treesitter node.
