### ISSUE TITLE
Failed to load with packadd

### ISSUE THREAD

**Issue by ray-x** [steelsojka/pears.nvim#22]
Minium vimrc:

```vim
call plug#begin('~/.vim/plugged')
" Plug 'steelsojka/pears.nvim'
call plug#end()
```
pears.nvim was cloned to $HOME/.vim/plugged/pears.nvim
Start nvim and 
Run `packadd pears.nvim`
Run `lua require "pears".setup()`
Both does not show any errors
And insert `(`,  it was not auto paired with ')'

**Comment by steelsojka** [comment]
I'm not sure if your setup is correct... I don't think vim-plug is suppose to work with packadd.

**Comment by ray-x** [comment]
packadd is an instruction provided by neovim and can be used without any plugin pre-installed.
Alternative I can 
clone pears.nvim in ~/.vim/pack

start nvim by
`nvim -u NORC`

And run `packadd pears.nvim` and then setup(). Pears still failed to load


Another try

```vim
call plug#begin('~/.vim/plugged')
Plug 'steelsojka/pears.nvim'
call plug#end()
```

After nvim loaded with above vimrc, run `lua require "pears".setup()` from command. Still no luck


I think one point is whether `pears.nvim` can be loaded later when I am in insert mode?

**Comment by ray-x** [comment]
Ok. if I open another file in buffer, pear back to life.
So the question is that is there a way to lazy load pear after Insert event.

**Comment by steelsojka** [comment]
You can call the attach method with the buffer id on any event you want. If
it is already attached its a noop.

**Comment by ray-x** [comment]
thanks.
Need to rerun `lua require("pears").attach()` for lazy loading. That works.
