### ISSUE TITLE
Filetype Black/Whitelist

### ISSUE THREAD

**Issue by theHamsta** [steelsojka/pears.nvim#3]
It would be nice to have a filetype white/blacklist or more general a config predicate function that could decide whether or not to attach to a buffer. So I could set a function that enables pears on every buffer except on Lisp buffers because I have other parenthesis handler for them.

**Comment by steelsojka** [comment]
Yep! Thats on my list of things to do. I will get that working sometime
this week.

**Comment by steelsojka** [comment]
@theHamsta Can you test the new api that I added for FT configuration and see if that fits your use case? Let me know if you have any other use cases I could add.

**Comment by theHamsta** [comment]
@steelsojka This is perfekt! When I call `lua require "pears".setup_buf_pairs {}` I can deactivate the plugin for the current buffer or I can just exclude the language for all pairs! Nice work!

**Comment by theHamsta** [comment]
Actually the plugin in could detach from the buffer when there are not pairs
