### ISSUE TITLE
question: not pairing if next character is  not whitespace or EOL

### ISSUE THREAD

**Issue by pwntester** [steelsojka/pears.nvim#35]
Hi,

I would like to not complete a pair if there is a character after the cursor. Eg:

Do not complete:
foo|{  ->  foo{|{

Complete:
foo|   ->  foo{|}

Im pretty sure this is currently possible but haven't found any example or documentation

Thanks!

**Comment by ram02z** [comment]
@pwntester 
For your specific example, add this to your pears setup function
```lua
conf.pair("{", {
  close = "}",
  should_expand = R.not_(R.match_next "[{]")
})
```

**Comment by pwntester** [comment]
Thanks
