### ISSUE TITLE
[Suggestion] User level pairings per filetype API

### ISSUE THREAD

**Issue by bluz71** [steelsojka/pears.nvim#4]
Hello,

I am an existing [pear-tree](https://github.com/tmsvg/pear-tree) user, but I am keeping a keen eye on the development of this interesting plugin.

One thing that is very nice about *pear-tree* is that it is very easy to define your own pairs per filetype, for example this is my `~/.vim/after/ftplugin/ruby.vim` file:

```viml
let b:pear_tree_pairs = {
            \ '(': {'closer': ')'},
            \ '[': {'closer': ']'},
            \ '{': {'closer': '}'},
            \ "'": {'closer': "'"},
            \ '"': {'closer': '"'},
            \ '|': {'closer': '|'},
            \ }
```

With Ruby I would like to define auto-close for the `|` character, but not for any other filetype. And this can then apply for other filetypes, for example triple back-quote only for Markdown.

Another cool thing about *pear-tree* is that it can auto-close tags (JSX for instance), for example this is my `~/.vim/after/ftplugin/javascript.vim` file:

```viml
let b:pear_tree_pairs = {
            \ '(':     {'closer': ')'},
            \ '[':     {'closer': ']'},
            \ '{':     {'closer': '}'},
            \ "'":     {'closer': "'"},
            \ '"':     {'closer': '"'},
            \ '`':     {'closer': '`'},
            \ '/\*\*': {'closer': '\*/'},
            \ '<*>':   {
            \            'closer':   '</*>',
            \            'not_if':   ['br', 'hr', 'img'],
            \            'not_like': '/$',
            \            'until':    '[^a-zA-Z0-9-._]'
            \          },
            \ }
```

It is up to you whether this is of interest or not, maybe it complicates things too much. But I decided it may be useful to let you know how folks are using existing auto-pairing plugins which may be of interest as you develop this plugin.

Best regards.

**Comment by steelsojka** [comment]
You can now define which pairs to include at the buffer level using `setup_buf_pairs()`. The only difference is pairs are configured in the setup call. You can also pass a config object when defining the pair that includes an inclusion/exclusion list of filetypes. Let me know if this meets you use case. I'm open to tweaking it to fit as many use cases as possible.

As far as wildcard pairing goes, it's not high on the priority list right now. I don't have the use case and that seems to be moving auto of scope of what I initially intended.... but I will take a look at it and see if it's possible to implement. I just want to get all the basics in first before I move on to some more advanced features.

**Comment by bluz71** [comment]
Thanks for the filetypes tip. Looks like the solution.

Wildcard pairing may be useful for tag pairing. It is up to you if you add that, i do know that vim-surround (from Tim Pope) and pear-tree both handle tags in the same way as quotes and bravkets. I use both plugins and I won't lie, it is very useful especially for JSX in JavaScript code.

Anyway, something for you to think about. Note, if you skip it, that is fine too. Closing this as to declutter your issues.

Best regards.

**Comment by steelsojka** [comment]
@bluz71 Thanks for the input! I added a barebones/rough implementation of wildcard pairs. I don't think it's as robust as pear-tree but it should cover the bases. I plan on refining it much more.

**Comment by bluz71** [comment]
Nice. So eventually, after this plugin is refined, it will be able to do tag pairing in addition to standard pairings.

I will indeed play with this work in progress plugin. My aim would be to replace pear-tree with this instead since I like Lua speed and Treesitter intelligence.

Keep up the good work, this plugin will eventually be very useful to quite a few Neovim users.
