### ISSUE TITLE
[Wildcard tag issue] Entering space will automatically create close tag, not desired

### ISSUE THREAD

**Issue by bluz71** [steelsojka/pears.nvim#5]
Hello again,

I am dipping my toe into this plugin. Developing very well. But I am aware it is still a work in progress.

Anyway, I do encounter a quirk with wildcard tag expansion.

My desire is type this JSX tag `<div className='AlbumShow'>`, however as soon as I type space after `div` the tag will automatically be paired `<div>|</div>`.

Personally I think pairing should only happen after `>` is entered.

Likewise I can't enter a self-closing tag such as `<Footer/>`, tag will be closed after `/` is typed.

I do think tag pairing will be a very useful addition to this plugin, so I am glad to see added.

Best regards.

**Comment by bluz71** [comment]
I should have noted I am using:

```lua
conf.preset "tag_matching"
```

**Comment by bluz71** [comment]
Oops, did not mean to close this.

**Comment by steelsojka** [comment]
Yeah, this was actually originally intended but I forgot you could put a space in an html tag (oops). I'll look at it and adjust the matching pattern.

**Comment by steelsojka** [comment]
I think it needs some tweaking. I'll work on it with these new scenarios.

**Comment by bluz71** [comment]
Sure, no rush at my end.

**Comment by steelsojka** [comment]
This should mostly be working now after my latest refactor. Let me know if it solves your use cases.

**Comment by bluz71** [comment]
Yes, looks to be solved.

Many thanks.
