### ISSUE TITLE
| pears |

### ISSUE THREAD

**Issue by salkin-mada** [steelsojka/pears.nvim#9]
Hey thanks for this nice auto pairs plugin.
I cant seem to get the `|` pairs to work.
even tried to set it specifically for one filetype ( no luck ):
```
        use {
            "steelsojka/pears.nvim",
            config = function()
                require 'pears'.setup(function(conf)
                    conf.pair("|", "|", {filetypes = {"supercollider"}})
                    conf.preset "tag_matching"
                end)
            end
        }

```
what am i doing wrong?

**Comment by steelsojka** [comment]
`pair` only takes two arguments, a string or a table. A string is shorthand for `{close = "|"}`. Change it to `conf.pair("|", {close = "|", filetypes = {"supercollider"})`

**Comment by salkin-mada** [comment]
ah true! thanks.
